#Aquí crearem els dos contenidors, un per l'aplicació de Spring boot i un altre contenidor per la base de dades PostgreSQL
version: "3.0"

services:
  postgres:
    image: postgres:17
    container_name: postgreSQL_database
    restart: always
    environment:
      POSTGRES_DB: tascaAndreu
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  ngnix:
    container_name: ngnix
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443"
    volumes:
      - "./ngnix/ngnix.conf:/etc/ngnix/ngnix.conf"

  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - "./certbot/conf:/etc/letsencrypt"
        - "./certbot/www:/var/www/certbot"
      command: "certonly --webroot -w /var/www/certbot --force-renewal --email angel.rubio@mindata.es -d pgmnt.xyz --agree-tos"

  app:
    build: .
    container_name: tascaAndreu_application
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tascaAndreu
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - "8080:8080"

volumes:
  postgres_data:
