name: Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: tascaAndreu
  CONTAINER_APP_NAME: tascaandreu
  RESOURCE_GROUP: DefaultResourceGroup-ESC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Convierte el nombre del ACR a minúsculas y lo guarda en GITHUB_ENV
      - name: Convert ACR name to lowercase
        run: echo "AZURE_CONTAINER_REGISTRY_LOWER=$(echo $AZURE_CONTAINER_REGISTRY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Configura Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Compila con Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Configura Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login en Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login en ACR con el nombre en minúsculas
      - name: Log in to ACR
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY_LOWER }}

      # Construye y sube la imagen Docker con el ACR en minúsculas
      - name: Build and push container image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile  # Asegúrate de que sea para Java
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_LOWER }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

      # Despliega en Azure Container Apps con el ACR en minúsculas
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY_LOWER }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          environmentVariables: |
            SPRING_PROFILES_ACTIVE=prod
